# Generated by Django 5.2.4 on 2025-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
