# Generated by Django 5.2.7 on 2025-11-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastconfig',
            name='include_promotions',
            field=models.BooleanField(default=True),
        ),
    ]
