# Generated by Django 5.2.4 on 2025-09-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
