# Generated by Django 5.2.4 on 2025-10-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='daily_mape',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
